### ISSUE TITLE
Set-up Github organization.

### ISSUE THREAD

**Issue by hribo98** [storygraph/story-graph#1]
:white_check_mark: Establish subtasks convention
:white_check_mark: Agree on standard git workflow and labels
:white_check_mark: Make clear how we organize code.
:white_check_mark: Create git wiki for project architecture/organization/major goals
:white_check_mark: [Research] How can we integrate automated tests/formatting in per PR/commit
:white_check_mark: Make acceptance criteria for PRs/Tasks
:white_check_mark: Add guidelines to notes

Progress:

New convention. Use:
- 💡 for in progress
- ✅ for done
- ❌ for won't do

Guidelines:
- [Refactoring guide](https://refactoring.guru/?fbclid=IwAR33p7i42NAOiGz3cEQ0amcMThmmjPtu1JqdnMWvscfnZWZqgP3UbuAb7dM)
- [Go code review guide](https://refactoring.guru/?fbclid=IwAR33p7i42NAOiGz3cEQ0amcMThmmjPtu1JqdnMWvscfnZWZqgP3UbuAb7dM)
- Use **gofmt**, **golint**, **shellcheck**
- Use LiveShare extension of VS Code for Remote Pairing
- [DOCUMENTATION] Use notes for shared docs. Embrace the use of Github wikis, by adding a bullet list on the README.md of each repo to it's specific wiki pages
- Separate Repo for Concourse CI/CD
- Use [KinD](https://github.com/kubernetes-sigs/kind) for bootstrapping k8s in docker container in CI/CD
- Run regression tests before merging PRs
- Enforce gofmt and golint as Github actions
- Embrace TDD (BDD?) with high test coverage (>= 90%)

**Comment by IvanHristov98** [comment]
New convention. Use:
- :bulb: for in progress
- :white_check_mark: for done
- :x: for won't do

**Comment by alfasketer** [comment]
az sam patka
az sam patka
woof
woof

**Comment by hribo98** [comment]
All tasks are done. Closing
